### PR TITLE
Added STL and STEP case models for v1.0.

### PR DESCRIPTION
**Pull request by s-gordon**
Added case models for v1.0. Includes bottom, top, and shell components. These have not been printed to establish that the fit is good #9

### CODE REVIEW

**Review by MeisterGig — COMMENTED** [review]
This looks nice even with the logo :). Could it be that the pins to attach the bottom to the top might break off?. It looks like, they would need to bend a lot. Especially in their printed direction, they might snap quite easily. Maybe you could make them a little bit smaller, so they don't need to bend so far :).  I'm gonna print this case over night anyways and see if it fits :)

**Comment by s-gordon** [comment]
@MeisterGig Thanks :-). Re: the pins/anchors, I'm honestly not sure about whether these will snap when attaching the top and bottom pieces. Happy to tweak this to reduce how far they extend out.

Keen to hear how this prints!

**Comment by s-gordon** [comment]
@MeisterGig I've shortened the pins by 2 mm to minimise the risk of snapping when assembling the two halves.

**Comment by MeisterGig** [comment]
Unfortunately i wasn't able to close it 🥺 The locking Pins interferes with the lip going around the edge. The lip prohibits the Case from bending to that the lib can snap in place.

This part would need to be able to bend out a little bit so the pin gets ito the hole:





Otherwise it seams to fit

**Comment by MeisterGig** [comment]
When one pin is broken of though, i am able to close it at an angle 


Although i just realized, that the USB Port ist now to high.

**Comment by s-gordon** [comment]
Hmm, that's not ideal. Thanks for taking the time to print this out.

The snap joints definitely sound like they're too flimsy for the job. I'll look into replacing these with something more robust; perhaps a wedge-style snap similar to what's been done [here](https://youtu.be/VVmOtM60VWw?t=1000).

I hadn't considered that the cutout for the USB port wouldn't be high enough. Oversight on my part. I'd developed the model assuming 8.4mm female header pins and a Wemos D1 mini ESP8266. Is that a Wemos S2 Mini that you've used? I'll rework the design to accommodate.

Any other issues with the build?

**Comment by s-gordon** [comment]
@MeisterGig - I've reworked the design to (hopefully) fix the issues that you flagged. I've modified both the top and bottom pieces, so you'll want to reprint both if you'd like to check. Notably I've removed the snaps and swapped to a raised-ridge style join to connect the top and bottom, and I've tweaked the power cable access hole to allow enough clearance for the S2 Mini and similar modules.

**Comment by MeisterGig** [comment]
Nice Thank you.  I've printed it and i can assemble it. The USB port also fits. So i am gonna merge it now :)  There might still be the problem, that the light sensor isn't recieving enough light, but i haven't tested that yet.

**Review by MeisterGig — APPROVED** [review]
Nice Thank you. I've printed it and i can assemble it. The USB port also fits. So i am gonna merge it now :) There might still be the problem, that the light sensor isn't recieving enough light, but i haven't tested that yet.

**Pull request merged**
