### PR TITLE
All changes for firmware 3.0.0

### PR DESCRIPTION
**Pull request by Schluggi**
## Todo:
- [x] substitutions for voice assistant 
- [x] voice assistant for ESP32-S2 mini
- [x] update docs theme
- [ ] documentation

## How to test?
Replace your existing config with [this config](https://raw.githubusercontent.com/Schluggi/AIOsense/ca2657c1370fb031b6cc64fef182da72558b5212/esphome/esphome.yaml).

## New features
- BSEC support (#122)
- GUI controlled offsets
- Offsets for air quality, VOC and CO2 (#122)
- Voice Assistant Support (cb1929a1c0d317d116c09bbcfd8b02839058e966)
- mmWave SEN0395 DFRobot now supports distance segments (#107)
  - You can define up to 4 zones based on distance where the radar does get triggered. This can be usefull if you have moving objects in front of the sensor

## Breaking changes
- The default `temperature_offset` is now `-6`
- **Deprecated:** Since we run out of IO pins all ESPs besides ESP32-S2-mini and ESP32-S3-mini are deprecated and will not longer fully supported in AIOsense PCB v3.0.0
- You must press the button "mmWave Apply Settings" after changes mmWave related settings
  - This improves the lifetime of the sensor because it is less often written to flash

## Other changes
- Using the official SEN0395 component instead of the custom component (#125)

Removed packages:
- `esphome/packages/sensors/bme680_bsec.yaml` -> Replaced with `esphome/packages/sensors/bme68x_bsec.yaml`

Removed substitutions:
- `bme680_bsec_sample_rate`
- `bme680_bsec_temperature_offset`

Renamed substitutions:
- `bmex80_address` -> `bme_address`
- `bmex80_update_interval` -> `bme680_bsec_temperature_offset`

### CODE REVIEW

**Comment by Qu4ndo** [comment]
Did a quick and dirty test with the changed config.
Sadly I did not get the voice assistant to work.
"Assist in Progress" did not change for me, but could also be a setup problem with the wakeword docker.

Tried to reference the sensor config with the one from lewis but couldn't find a major difference:
https://gist.github.com/EverythingSmartHome/055fbdde31a607ef9d695d5cac780e94 

BSEC worked out of the box.

-> AIO 2.0.0 PCB
-> ESP32-C3 Board

**Comment by Schluggi** [comment]
@Qu4ndo, I used these docker containers with there example command. 

- https://hub.docker.com/r/rhasspy/wyoming-openwakeword
- https://hub.docker.com/r/rhasspy/wyoming-piper
- https://hub.docker.com/r/rhasspy/wyoming-whisper

The 2.0.0 PCB should also work fine.
For me as a Home Assistant Container user, `media_source` and `conversation` was missing in my configuration file. I also notice the assistant pipeline needs a TTS provider. Otherwise it does not work. 

This may help?

**Comment by Qu4ndo** [comment]
Thanks for the links.
I found the debugging under: assistant config > three dots > debugging
After that I could test the pipeline with my wakeword -> worked fine with my notebook

At the moment I'm not sure if I have a networking (because different subnets), hardware (microphone) or some config issue.
The microphone stream is received by the wakeword docker, but nothing happens after that.
So the connection seems fine. Could also be a hardware issue with a defect microphone ... I don't know

Tried the wav file output in the homeassistant config, but I only got them when rebooting, which means there was no audio because the're empty.

Found a weird behaviour after (re-)boots:
With the rgb_led.yaml package enabled (needed for VA), the led turns on and off after bootup.
This probably overwrites the VA LED setting, because the indication light won't turn on (except if toggled off and on manually).

I also can't turn off and on the VA Switch to fast because otherwise the microphone or pipeline defaults to an error loop (in ESPHome Log). Around 2-5 seconds is mostly fine.

**Comment by Schluggi** [comment]
@Qu4ndo, please try again. I've add some boot fixes. The LED should now blink twice to indicate the starting. Afterwards the VA LED should light up to indicate VA is active.

If this does not fix your problem:
- Please share your ESPHome & HA Log 
- Does the wyoming-piper container receive your voice?

**Comment by Ghome79** [comment]
@Schluggi
esphome/packages/sensors/voice_assistant_led.yaml  # esp32-s2 only

file missing

**Comment by Schluggi** [comment]
> file missing

Yes. This is WIP and not feature complete yet :)
I'll fix it by time.

**Comment by Qu4ndo** [comment]
After some really annoying testing I found a fix for my networking problem.
My homeassistant server is on the other side of a side-to-side vpn, so in order to redirect the esp udp traffic (with random ports) to the server instance I had to set a 1:1 NAT. Sadly you can't set a static IP for the homeassistant instance on the esp itself.

After that try and error the microphone works like a charm and I can control my home with my voice!

@Schluggi Thank you for the great work!

**Comment by Ghome79** [comment]
After a lot of annoying testing lol. I tested 4 microphones with a simple Arduino sketch with serial plotter and 3 of my mics were defective and don't work whatsoever and the last one i need to shout at it from a couple of centimeter to work . maybe a bad batch or flux damage it while soldering. who knows.

**Pull request merged**
